//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHue3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinHue3.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object created successfully!.
        /// </summary>
        public static string AdvancedCreator_ObjectCreated {
            get {
                return ResourceManager.GetString("AdvancedCreator_ObjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending a delete request will most likely delete the specified object. Delete?.
        /// </summary>
        public static string AdvancedCreator_WarningDelete {
            get {
                return ResourceManager.GetString("AdvancedCreator_WarningDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY CONNECTED.
        /// </summary>
        public static string Already_Connected {
            get {
                return ResourceManager.GetString("Already_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating firmware... The program will not respond for 2 minutes during the update..
        /// </summary>
        public static string ApplyingUpdate {
            get {
                return ResourceManager.GetString("ApplyingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bridge is already present in the list of bridges. Please enter another IP address..
        /// </summary>
        public static string Bridge_Already_Detected {
            get {
                return ResourceManager.GetString("Bridge_Already_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying bridge update... The bridge might become unresponsive for a minute or two..
        /// </summary>
        public static string Bridge_ApplyingUpdate {
            get {
                return ResourceManager.GetString("Bridge_ApplyingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from bridge..
        /// </summary>
        public static string Bridge_Disconnected {
            get {
                return ResourceManager.GetString("Bridge_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bridge {0} seems to have changed IP. Do you want to replace the current IP Address?.
        /// </summary>
        public static string Bridge_IP_Different {
            get {
                return ResourceManager.GetString("Bridge_IP_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new lights for 1 minute..
        /// </summary>
        public static string Bridge_LightSearch {
            get {
                return ResourceManager.GetString("Bridge_LightSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect....
        /// </summary>
        public static string Bridge_Menu_Connect {
            get {
                return ResourceManager.GetString("Bridge_Menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Bridge_Menu_Disconnect {
            get {
                return ResourceManager.GetString("Bridge_Menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Bridge_Menu_Settings {
            get {
                return ResourceManager.GetString("Bridge_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Bridge_Menu_Update {
            get {
                return ResourceManager.GetString("Bridge_Menu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not signed in.
        /// </summary>
        public static string Bridge_Not_Signed_In {
            get {
                return ResourceManager.GetString("Bridge_Not_Signed_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bridge you would like to control with WinHue..
        /// </summary>
        public static string Bridge_SelectOne {
            get {
                return ResourceManager.GetString("Bridge_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed In.
        /// </summary>
        public static string Bridge_Signed_In {
            get {
                return ResourceManager.GetString("Bridge_Signed_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Access Denied.
        /// </summary>
        public static string BridgeAccessDenied {
            get {
                return ResourceManager.GetString("BridgeAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Connected.
        /// </summary>
        public static string BridgeConnected {
            get {
                return ResourceManager.GetString("BridgeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing started. Please press the link button on the bridge to finish pairing..
        /// </summary>
        public static string BridgeDetectionPairing_Pairing {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_Pairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing complete. Please select another bridge to begin another pairing or select a default bridge to complete the procedure..
        /// </summary>
        public static string BridgeDetectionPairing_PairingDone {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_PairingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pair at least one bridge..
        /// </summary>
        public static string BridgeDetectionPairing_PairNeeded {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_PairNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning aborted..
        /// </summary>
        public static string BridgeDetectionPairing_ScanAborted {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_ScanAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning complete..
        /// </summary>
        public static string BridgeDetectionPairing_ScanComplete {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for bridge... please wait..
        /// </summary>
        public static string BridgeDetectionPairing_Scanning {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bridge and press Pair in order to begin pairing procedure..
        /// </summary>
        public static string BridgeDetectionPairing_SelectionMessage {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_SelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default bridge not set..
        /// </summary>
        public static string BridgeDetectionPairing_SetDefault {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSDP and UPNP are not activated. Please activate them in order to get better detection of the bridge..
        /// </summary>
        public static string BridgeDetectionPairing_Upnp_Not_Working {
            get {
                return ResourceManager.GetString("BridgeDetectionPairing_Upnp_Not_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disconnect from the bridge?.
        /// </summary>
        public static string BridgeDisconnect {
            get {
                return ResourceManager.GetString("BridgeDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge not paired or authorized. Do you want to proceed with the pairing procedure?.
        /// </summary>
        public static string BridgeSetupNotCompleted {
            get {
                return ResourceManager.GetString("BridgeSetupNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to bridge {0} . Please make sure that it is properly connected to the network..
        /// </summary>
        public static string BridgeUnableToConnect {
            get {
                return ResourceManager.GetString("BridgeUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new updates. Please come back later to see if new updates are available..
        /// </summary>
        public static string CheckingForUpdate {
            get {
                return ResourceManager.GetString("CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color temperature cannot be selected at the same time as Hue or Saturation. .
        /// </summary>
        public static string ColorTempWarning {
            get {
                return ResourceManager.GetString("ColorTempWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0}?.
        /// </summary>
        public static string Confirm_Delete_Object {
            get {
                return ResourceManager.GetString("Confirm_Delete_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTED!.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press the LINK button now and press OK to continue..
        /// </summary>
        public static string Create_User_Press_Link {
            get {
                return ResourceManager.GetString("Create_User_Press_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must not be empty and must be of the DDD.DDDD{N|S} format..
        /// </summary>
        public static string Daylight_Latitude_Error {
            get {
                return ResourceManager.GetString("Daylight_Latitude_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must not be empty and must be of the DDD.DDDD{E|W} format..
        /// </summary>
        public static string Daylight_Longitude_Error {
            get {
                return ResourceManager.GetString("Daylight_Longitude_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling DHCP enables manual IP address..
        /// </summary>
        public static string Disable_DHCP {
            get {
                return ResourceManager.GetString("Disable_DHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Finished..
        /// </summary>
        public static string Done_Searching {
            get {
                return ResourceManager.GetString("Done_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object already exists in the canvas..
        /// </summary>
        public static string ElementExists {
            get {
                return ResourceManager.GetString("ElementExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bridge name cannot be empty or blank..
        /// </summary>
        public static string Error_Bridge_Name {
            get {
                return ResourceManager.GetString("Error_Bridge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bridge is not responding. .
        /// </summary>
        public static string Error_Bridge_Not_Responding {
            get {
                return ResourceManager.GetString("Error_Bridge_Not_Responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while applying the brige new settings. See the log for more details..
        /// </summary>
        public static string Error_Bridge_Settings {
            get {
                return ResourceManager.GetString("Error_Bridge_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occured.
        /// </summary>
        public static string Error_Bridge_Unknown {
            get {
                return ResourceManager.GetString("Error_Bridge_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Not Found.
        /// </summary>
        public static string Error_BridgeNotFound {
            get {
                return ResourceManager.GetString("Error_BridgeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the user..
        /// </summary>
        public static string Error_Create_User {
            get {
                return ResourceManager.GetString("Error_Create_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while creating a new scene. Please chech the event log for more details..
        /// </summary>
        public static string Error_Creating_Scene {
            get {
                return ResourceManager.GetString("Error_Creating_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string Error_ErrorHasOccured {
            get {
                return ResourceManager.GetString("Error_ErrorHasOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected gateway is invalid..
        /// </summary>
        public static string Error_Gateway_Invalid {
            get {
                return ResourceManager.GetString("Error_Gateway_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the basic bridge configuration..
        /// </summary>
        public static string Error_Getting_Bridge_Basic_Config {
            get {
                return ResourceManager.GetString("Error_Getting_Bridge_Basic_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while getting the bridge settings.  Please try reopening the window..
        /// </summary>
        public static string Error_Getting_BridgeSettings {
            get {
                return ResourceManager.GetString("Error_Getting_BridgeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while fetching groups.  Please try reopening the window..
        /// </summary>
        public static string Error_Getting_Groups {
            get {
                return ResourceManager.GetString("Error_Getting_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while fetching lights. Please try reopening the window..
        /// </summary>
        public static string Error_Getting_Lights {
            get {
                return ResourceManager.GetString("Error_Getting_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while getting new lights..
        /// </summary>
        public static string Error_Getting_NewLights {
            get {
                return ResourceManager.GetString("Error_Getting_NewLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while getting new sensors..
        /// </summary>
        public static string Error_Getting_NewSensors {
            get {
                return ResourceManager.GetString("Error_Getting_NewSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey already assigned by another process. Please select another key combo and try again..
        /// </summary>
        public static string Error_Hotkey_Already_Assigned {
            get {
                return ResourceManager.GetString("Error_Hotkey_Already_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port value..
        /// </summary>
        public static string Error_InvalidPort {
            get {
                return ResourceManager.GetString("Error_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least 4 characters long.
        /// </summary>
        public static string Error_Must_Be_4_Char {
            get {
                return ResourceManager.GetString("Error_Must_Be_4_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected netmask is invalid..
        /// </summary>
        public static string Error_NetMask_Invalid {
            get {
                return ResourceManager.GetString("Error_NetMask_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid API Key found.
        /// </summary>
        public static string Error_No_API_key_found {
            get {
                return ResourceManager.GetString("Error_No_API_key_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid IP Found.
        /// </summary>
        public static string Error_No_Valid_IP {
            get {
                return ResourceManager.GetString("Error_No_Valid_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy address is invalid..
        /// </summary>
        public static string Error_Prox_Address {
            get {
                return ResourceManager.GetString("Error_Prox_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The was an error removing the desired user..
        /// </summary>
        public static string Error_Remove_User {
            get {
                return ResourceManager.GetString("Error_Remove_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while renaming the object. Please check the event log for more details..
        /// </summary>
        public static string Error_Renaming {
            get {
                return ResourceManager.GetString("Error_Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition time must be a value between 0 and 65535.
        /// </summary>
        public static string Error_ScheduleInvalidTT {
            get {
                return ResourceManager.GetString("Error_ScheduleInvalidTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time must be a valid HH:mm:ss value..
        /// </summary>
        public static string Error_ScheduleTimeInvalid {
            get {
                return ResourceManager.GetString("Error_ScheduleTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while sending the all lights OFF command..
        /// </summary>
        public static string Error_Sending_AllOFF {
            get {
                return ResourceManager.GetString("Error_Sending_AllOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while sending the all lights ON command..
        /// </summary>
        public static string Error_Sending_AllON {
            get {
                return ResourceManager.GetString("Error_Sending_AllON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout occured while trying to contact the philips hue portal. Please try again later..
        /// </summary>
        public static string Error_Timout_Portal {
            get {
                return ResourceManager.GetString("Error_Timout_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least an App Name in order to create a user..
        /// </summary>
        public static string Error_Usermanager_NoDevType {
            get {
                return ResourceManager.GetString("Error_Usermanager_NoDevType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username cannot begin with a white space and must be between 10 and 40 characters..
        /// </summary>
        public static string Error_Username {
            get {
                return ResourceManager.GetString("Error_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloned Object not found in the list. Please edit the object manually..
        /// </summary>
        public static string Error_While_Cloning {
            get {
                return ResourceManager.GetString("Error_While_Cloning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occured while creating the object :.
        /// </summary>
        public static string Error_WhileCreatingObject {
            get {
                return ResourceManager.GetString("Error_WhileCreatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving..
        /// </summary>
        public static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string Field_Empty {
            get {
                return ResourceManager.GetString("Field_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A floor plan by that name already exists. Overwrite ?.
        /// </summary>
        public static string FloorPlanExists {
            get {
                return ResourceManager.GetString("FloorPlanExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic presets are hotkeys that do not have an object associated to them and can be applied to one or more object type on the bridge. Non generic are associated with at specific object of the bridge and will only apply to them..
        /// </summary>
        public static string Form_Hotkey_Help_Generic {
            get {
                return ResourceManager.GetString("Form_Hotkey_Help_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group name {0} already exists. Please select another name and try again..
        /// </summary>
        public static string Group_Already_Exists {
            get {
                return ResourceManager.GetString("Group_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} created sucessfully..
        /// </summary>
        public static string Group_Create_Success {
            get {
                return ResourceManager.GetString("Group_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while creating group {0}..
        /// </summary>
        public static string Group_Creation_Error {
            get {
                return ResourceManager.GetString("Group_Creation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group?.
        /// </summary>
        public static string Group_Delete {
            get {
                return ResourceManager.GetString("Group_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group_Group {
            get {
                return ResourceManager.GetString("Group_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group has been succesfully modified..
        /// </summary>
        public static string Group_Modified_Success {
            get {
                return ResourceManager.GetString("Group_Modified_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group name must be at least one character..
        /// </summary>
        public static string Group_Name_Error {
            get {
                return ResourceManager.GetString("Group_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one bulb in order to create a group..
        /// </summary>
        public static string Group_Select_One_Light {
            get {
                return ResourceManager.GetString("Group_Select_One_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling tablet mode will make the toolbar icons, trackbar thumbs as well as the hue picker thumb bigger for better control on a tablet..
        /// </summary>
        public static string Help_String_Tablet_Mode {
            get {
                return ResourceManager.GetString("Help_String_Tablet_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey already exists. Replace?.
        /// </summary>
        public static string HotKey_Already_Exists {
            get {
                return ResourceManager.GetString("HotKey_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill at least one property..
        /// </summary>
        public static string Hotkey_FillOneProperty {
            get {
                return ResourceManager.GetString("Hotkey_FillOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please record an hotkey.
        /// </summary>
        public static string Hotkey_RecordHotkey {
            get {
                return ResourceManager.GetString("Hotkey_RecordHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bridge object..
        /// </summary>
        public static string Hotkey_SelectObject {
            get {
                return ResourceManager.GetString("Hotkey_SelectObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type of bridge object..
        /// </summary>
        public static string Hotkey_SelectObjectType {
            get {
                return ResourceManager.GetString("Hotkey_SelectObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button {0} selected..
        /// </summary>
        public static string HueTap_ButtonSelected {
            get {
                return ResourceManager.GetString("HueTap_ButtonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No button selected..
        /// </summary>
        public static string HueTap_NoButtonSelected {
            get {
                return ResourceManager.GetString("HueTap_NoButtonSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a button in order to chose it&apos;s action..
        /// </summary>
        public static string HueTap_SelectAButton {
            get {
                return ResourceManager.GetString("HueTap_SelectAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scene selected. Please select a scene and press assign again..
        /// </summary>
        public static string HueTap_SelectAScene {
            get {
                return ResourceManager.GetString("HueTap_SelectAScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An firmware update available but not ready..
        /// </summary>
        public static string IncomingUpdate {
            get {
                return ResourceManager.GetString("IncomingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on line {0}, column {1}..
        /// </summary>
        public static string Interpreter_Error {
            get {
                return ResourceManager.GetString("Interpreter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error found..
        /// </summary>
        public static string Interpreter_NoError {
            get {
                return ResourceManager.GetString("Interpreter_NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected IP address is in an invalid format..
        /// </summary>
        public static string Invalid_IP {
            get {
                return ResourceManager.GetString("Invalid_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mood file.
        /// </summary>
        public static string Invalid_Mood_file {
            get {
                return ResourceManager.GetString("Invalid_Mood_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value does not convert to the requested property type..
        /// </summary>
        public static string Invalid_Rule_Action_Conversion {
            get {
                return ResourceManager.GetString("Invalid_Rule_Action_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene file invalid .
        /// </summary>
        public static string Invalid_Scene_File {
            get {
                return ResourceManager.GetString("Invalid_Scene_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered string is not valid.
        /// </summary>
        public static string InvalidString {
            get {
                return ResourceManager.GetString("InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application in order to apply language change..
        /// </summary>
        public static string Language_Change_Warning {
            get {
                return ResourceManager.GetString("Language_Change_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this light?.
        /// </summary>
        public static string Light_Delete {
            get {
                return ResourceManager.GetString("Light_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light_Type_Lights {
            get {
                return ResourceManager.GetString("Light_Type_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lights directory has not been found. Creating it....
        /// </summary>
        public static string Lights_DirectoryDoesNotExists {
            get {
                return ResourceManager.GetString("Lights_DirectoryDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not been pressed.
        /// </summary>
        public static string Link_Not_Pressed {
            get {
                return ResourceManager.GetString("Link_Not_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been pressed.
        /// </summary>
        public static string Link_Pressed {
            get {
                return ResourceManager.GetString("Link_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press the link button located on the bridge..
        /// </summary>
        public static string LinkButton_Not_Pressed {
            get {
                return ResourceManager.GetString("LinkButton_Not_Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Found! Please press the link button to finish pairing..
        /// </summary>
        public static string Manual_Bridge_Found {
            get {
                return ResourceManager.GetString("Manual_Bridge_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bridge found at this IP address..
        /// </summary>
        public static string Manual_Bridge_Not_Found {
            get {
                return ResourceManager.GetString("Manual_Bridge_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood folder is missing.
        /// </summary>
        public static string Mood_Missing_Folder {
            get {
                return ResourceManager.GetString("Mood_Missing_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Mood with this name already exists. Overwrite?.
        /// </summary>
        public static string Moods_AlreadyExists {
            get {
                return ResourceManager.GetString("Moods_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this mood?.
        /// </summary>
        public static string Moods_Delete {
            get {
                return ResourceManager.GetString("Moods_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name entered for the mood. Please enter a name..
        /// </summary>
        public static string Moods_Missing_Name {
            get {
                return ResourceManager.GetString("Moods_Missing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Values for mood are invalid. Please enter at least one value for the mood..
        /// </summary>
        public static string Moods_NotValidValues {
            get {
                return ResourceManager.GetString("Moods_NotValidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update has been downloaded. Do you want to update now?.
        /// </summary>
        public static string NewUpdateDownloaded {
            get {
                return ResourceManager.GetString("NewUpdateDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No light selected. Please chose a light for this marker..
        /// </summary>
        public static string No_Light_Selected {
            get {
                return ResourceManager.GetString("No_Light_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new messages..
        /// </summary>
        public static string No_New_Messages {
            get {
                return ResourceManager.GetString("No_New_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge firmware up to date..
        /// </summary>
        public static string NoFirmwareUpdate {
            get {
                return ResourceManager.GetString("NoFirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT CONNECTED.
        /// </summary>
        public static string Not_Connected {
            get {
                return ResourceManager.GetString("Not_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the object ? Does it still exists ?.
        /// </summary>
        public static string Object_Does_Not_Exists {
            get {
                return ResourceManager.GetString("Object_Does_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string Plugin_Settings {
            get {
                return ResourceManager.GetString("Plugin_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin {0} has caused an exception. The plugin will be disabled in order to prevent a crash. A plugin exception file will be generated in WinHue folder..
        /// </summary>
        public static string Plugins_Error {
            get {
                return ResourceManager.GetString("Plugins_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins directory found. Creating a new one..
        /// </summary>
        public static string Plugins_NoDirectory {
            get {
                return ResourceManager.GetString("Plugins_NoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to change name..
        /// </summary>
        public static string Press_Enter_To_Change_Name {
            get {
                return ResourceManager.GetString("Press_Enter_To_Change_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &apos;none&apos; for no proxy..
        /// </summary>
        public static string Proxy_NONE {
            get {
                return ResourceManager.GetString("Proxy_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user is not administrator. This application requires administrative privileges in order to work properly. Please restart the application with administrative rights or right click properties on the executable and click &quot;Run as administrator&quot;..
        /// </summary>
        public static string Require_admin {
            get {
                return ResourceManager.GetString("Require_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the resource link..
        /// </summary>
        public static string ResourceLinks_NameNeeded {
            get {
                return ResourceManager.GetString("ResourceLinks_NameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one resource for this resource link,.
        /// </summary>
        public static string ResourceLinks_SelectAtLeastOne {
            get {
                return ResourceManager.GetString("ResourceLinks_SelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This criteria already exists. Replace?.
        /// </summary>
        public static string RssFeedMonitor_CriteriaAlreadyExists {
            get {
                return ResourceManager.GetString("RssFeedMonitor_CriteriaAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace the selected action?.
        /// </summary>
        public static string Rule_ActionAlreadyExists {
            get {
                return ResourceManager.GetString("Rule_ActionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule action cannot be edited in this editor..
        /// </summary>
        public static string Rule_CannotBeEdited {
            get {
                return ResourceManager.GetString("Rule_CannotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A similar condition already exists. Do you want to replace it?.
        /// </summary>
        public static string Rule_ConditionAlreadyExists {
            get {
                return ResourceManager.GetString("Rule_ConditionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this rule?.
        /// </summary>
        public static string Rule_Delete {
            get {
                return ResourceManager.GetString("Rule_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body field cannot be empty..
        /// </summary>
        public static string Rule_EmptyBody {
            get {
                return ResourceManager.GetString("Rule_EmptyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur while creating the rule:.
        /// </summary>
        public static string Rule_ErrorCreating {
            get {
                return ResourceManager.GetString("Rule_ErrorCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The json string entered in the body field is invalid..
        /// </summary>
        public static string Rule_InvalidJson {
            get {
                return ResourceManager.GetString("Rule_InvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of actions reached. Please delete an action in order to add a new one..
        /// </summary>
        public static string Rule_MaxAction {
            get {
                return ResourceManager.GetString("Rule_MaxAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amout of conditions has been reached. Remove an existing condition in order to add a new one..
        /// </summary>
        public static string Rule_MaxConditions {
            get {
                return ResourceManager.GetString("Rule_MaxConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid rule name..
        /// </summary>
        public static string Rule_NameError {
            get {
                return ResourceManager.GetString("Rule_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need at least one action and one condition to create a new rule..
        /// </summary>
        public static string Rule_NeedsActionAndCondition {
            get {
                return ResourceManager.GetString("Rule_NeedsActionAndCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one action..
        /// </summary>
        public static string Rule_NoAction {
            get {
                return ResourceManager.GetString("Rule_NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one Action object..
        /// </summary>
        public static string Rule_NoActionObject {
            get {
                return ResourceManager.GetString("Rule_NoActionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one condition to the rule and try again..
        /// </summary>
        public static string Rule_NoCondition {
            get {
                return ResourceManager.GetString("Rule_NoCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a property and try again..
        /// </summary>
        public static string Rule_NoPropertySelected {
            get {
                return ResourceManager.GetString("Rule_NoPropertySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule not found. Please make sure that the rule still exists..
        /// </summary>
        public static string Rule_NotFound {
            get {
                return ResourceManager.GetString("Rule_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not of the proper format for the type : {0}.
        /// </summary>
        public static string Rule_NotProperFormat {
            get {
                return ResourceManager.GetString("Rule_NotProperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original object of this rule was not found. Please make sure the object still exists in the bridge and try again..
        /// </summary>
        public static string Rule_OriginalObjectNotFound {
            get {
                return ResourceManager.GetString("Rule_OriginalObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} has already been set. Replace it?.
        /// </summary>
        public static string Rule_PropertyAlreadyExists {
            get {
                return ResourceManager.GetString("Rule_PropertyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace the selected action?.
        /// </summary>
        public static string Rule_ReplaceAction {
            get {
                return ResourceManager.GetString("Rule_ReplaceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace this condition?.
        /// </summary>
        public static string Rule_ReplaceCondition {
            get {
                return ResourceManager.GetString("Rule_ReplaceCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry the selected object not found. Does it still exists ?.
        /// </summary>
        public static string Rule_SelectedObjectDoesNotExists {
            get {
                return ResourceManager.GetString("Rule_SelectedObjectDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sensor in order to create a condition..
        /// </summary>
        public static string Rule_SelectSensor {
            get {
                return ResourceManager.GetString("Rule_SelectSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor ressource cannot be empty. Please specify a sensor ressource..
        /// </summary>
        public static string Rule_SensorRes {
            get {
                return ResourceManager.GetString("Rule_SensorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value field cannot be empty..
        /// </summary>
        public static string Rule_ValueEmpty {
            get {
                return ResourceManager.GetString("Rule_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not within the max and min for the type:.
        /// </summary>
        public static string Rule_ValueNotInRange {
            get {
                return ResourceManager.GetString("Rule_ValueNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that both X and Y are correctly filled..
        /// </summary>
        public static string Rule_XYError {
            get {
                return ResourceManager.GetString("Rule_XYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the settings..
        /// </summary>
        public static string SaveSettings_Error {
            get {
                return ResourceManager.GetString("SaveSettings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Scene with this name already exists. Overwrite?.
        /// </summary>
        public static string Scene_AlreadyExists {
            get {
                return ResourceManager.GetString("Scene_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the current scene?.
        /// </summary>
        public static string Scene_Clear_Warning {
            get {
                return ResourceManager.GetString("Scene_Clear_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete that scene?.
        /// </summary>
        public static string Scene_Delete {
            get {
                return ResourceManager.GetString("Scene_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load the RGB Image?.
        /// </summary>
        public static string Scene_Load_RGB {
            get {
                return ResourceManager.GetString("Scene_Load_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scene folder is missing... recreating it..
        /// </summary>
        public static string Scene_MissingFolder {
            get {
                return ResourceManager.GetString("Scene_MissingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scene name is invalid..
        /// </summary>
        public static string Scene_Name_Invalid {
            get {
                return ResourceManager.GetString("Scene_Name_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scene in this rule does not exist anymore..
        /// </summary>
        public static string Scene_NotFound {
            get {
                return ResourceManager.GetString("Scene_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace scene light state with current state?.
        /// </summary>
        public static string Scene_Replace_Current_States {
            get {
                return ResourceManager.GetString("Scene_Replace_Current_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        public static string Scene_Scene {
            get {
                return ResourceManager.GetString("Scene_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check at least one bulb..
        /// </summary>
        public static string Scene_Select_At_Least_One_Light {
            get {
                return ResourceManager.GetString("Scene_Select_At_Least_One_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must at least select one light..
        /// </summary>
        public static string Scene_SelectOneLight {
            get {
                return ResourceManager.GetString("Scene_SelectOneLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string Schedule_Alarm {
            get {
                return ResourceManager.GetString("Schedule_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Schedule?.
        /// </summary>
        public static string Schedule_Delete {
            get {
                return ResourceManager.GetString("Schedule_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule_Schedule {
            get {
                return ResourceManager.GetString("Schedule_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one day of the week to repeat the alarm..
        /// </summary>
        public static string Schedule_SelectAtLeastOneDay {
            get {
                return ResourceManager.GetString("Schedule_SelectAtLeastOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Schedule_Timer {
            get {
                return ResourceManager.GetString("Schedule_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found.
        /// </summary>
        public static string Schedule_Unknown_Group {
            get {
                return ResourceManager.GetString("Schedule_Unknown_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light not found.
        /// </summary>
        public static string Schedule_Unknown_Light {
            get {
                return ResourceManager.GetString("Schedule_Unknown_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene not found.
        /// </summary>
        public static string Schedule_Unknown_Scene {
            get {
                return ResourceManager.GetString("Schedule_Unknown_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new lights....
        /// </summary>
        public static string Searching_Lights {
            get {
                return ResourceManager.GetString("Searching_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for new sensors....
        /// </summary>
        public static string Searching_Sensors {
            get {
                return ResourceManager.GetString("Searching_Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a light or group..
        /// </summary>
        public static string Select_Light_Group {
            get {
                return ResourceManager.GetString("Select_Light_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one light to be previewed..
        /// </summary>
        public static string Select_One_Light {
            get {
                return ResourceManager.GetString("Select_One_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this sensor?.
        /// </summary>
        public static string Sensor_Delete {
            get {
                return ResourceManager.GetString("Sensor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        public static string Sensor_EmptyField_Error {
            get {
                return ResourceManager.GetString("Sensor_EmptyField_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during communication..
        /// </summary>
        public static string Sensor_Error {
            get {
                return ResourceManager.GetString("Sensor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be at least 6 characters long..
        /// </summary>
        public static string Sensor_FieldTooShort {
            get {
                return ResourceManager.GetString("Sensor_FieldTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure that all textboxes are filled with required information and that the URL is valid..
        /// </summary>
        public static string Sensor_InvalidFields {
            get {
                return ResourceManager.GetString("Sensor_InvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified URL is invalid. A valid URL begins with http:// ..
        /// </summary>
        public static string Sensor_InvalidURL {
            get {
                return ResourceManager.GetString("Sensor_InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Value.
        /// </summary>
        public static string Sensor_TestUrl {
            get {
                return ResourceManager.GetString("Sensor_TestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact sensor. Please make sure that the sensor url is valid..
        /// </summary>
        public static string Sensor_UnableToComm {
            get {
                return ResourceManager.GetString("Sensor_UnableToComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one serial number..
        /// </summary>
        public static string SerialCannotBeEmpty_Error {
            get {
                return ResourceManager.GetString("SerialCannotBeEmpty_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address set to:: .
        /// </summary>
        public static string Settings_ChangeIp {
            get {
                return ResourceManager.GetString("Settings_ChangeIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to test gradient. Please make sure that you have a value for the start and stop temperature as well as a light selected to test on..
        /// </summary>
        public static string Settings_CPU_Temp_NoValue {
            get {
                return ResourceManager.GetString("Settings_CPU_Temp_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Entering the settings will disable all plugins. Are you sure you want to modify the settings?.
        /// </summary>
        public static string Settings_DisableAllTools {
            get {
                return ResourceManager.GetString("Settings_DisableAllTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must press the link button to enable the button..
        /// </summary>
        public static string Tooltip_UserManager_CreateUser {
            get {
                return ResourceManager.GetString("Tooltip_UserManager_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Device Type to identify your device in the bridge.
        /// </summary>
        public static string Tooltip_UserManager_DeviceType {
            get {
                return ResourceManager.GetString("Tooltip_UserManager_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or Generate a username which is a unique string to identify your device..
        /// </summary>
        public static string Tooltip_UserManager_Username {
            get {
                return ResourceManager.GetString("Tooltip_UserManager_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export the requested config.
        /// </summary>
        public static string UnableToExport {
            get {
                return ResourceManager.GetString("UnableToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the update?.
        /// </summary>
        public static string Update_Confirmation {
            get {
                return ResourceManager.GetString("Update_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check every # minute(s).
        /// </summary>
        public static string Update_Delay_String {
            get {
                return ResourceManager.GetString("Update_Delay_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading update status..
        /// </summary>
        public static string Update_Error {
            get {
                return ResourceManager.GetString("Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new bridge firmware is available..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available. Do you want to download it?.
        /// </summary>
        public static string UpdateAvailableDownload {
            get {
                return ResourceManager.GetString("UpdateAvailableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user?.
        /// </summary>
        public static string UserManager_RemoveUser {
            get {
                return ResourceManager.GetString("UserManager_RemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Your bridge API version is not up to date. WinHue will not work properly unless you have the latest version of the bridge API. Please update your bridge API to the latest version..
        /// </summary>
        public static string Warning_Bridge_Not_Updated {
            get {
                return ResourceManager.GetString("Warning_Bridge_Not_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application to apply the new language..
        /// </summary>
        public static string Warning_ChangeLanguage {
            get {
                return ResourceManager.GetString("Warning_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this mood?.
        /// </summary>
        public static string Warning_Delete_Effect {
            get {
                return ResourceManager.GetString("Warning_Delete_Effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Transition Time is longer than 3 seconds! You will not be able see your preview properly and the light will revert to their previous state after 3 seconds..
        /// </summary>
        public static string Warning_TransitionTime {
            get {
                return ResourceManager.GetString("Warning_TransitionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A plan has been modified. If you continue you will lose your modifications. Continue ?.
        /// </summary>
        public static string WarnModifiedPlan {
            get {
                return ResourceManager.GetString("WarnModifiedPlan", resourceCulture);
            }
        }
    }
}
